<font color="green">To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.</font>

# Python Programming:  Simple Random Sampling

## Importing our Libraries

In [2]:
# importing numpy
import numpy as np

# importing pandas
import pandas as pd

# importing random module
# we will use random.sample() function to return a k length 
# list of unique elements chosen from our population
import random

## 1.0 Selecting More than One item from a List

In [3]:
# Example 1
# ---
# Selecting more than one item from a list 
# ---
#

list = [20, 40, 80, 100, 120]
print ("Choosing 3 random items from a list using sample function", random.sample(list, k=3))

list = [20, 40, 20, 20, 20]
print ("Choosing 3 random items from a list using sample function",random.sample(list, k=3))

# As you can see we pass k=3 to choose 3 random elements from a list. 
# In return, we got a list of 3 random items.

Choosing 3 random items from a list using sample function [80, 120, 20]
Choosing 3 random items from a list using sample function [20, 20, 20]

### <font color="green"> 1.0 Challenges</font>

In [4]:
# Challenge 1
# ---
# Question: Create a list containing 10 counties in Kenya 
# then select 2 random counties from the list.
# ---
# 
counties = ['Nairobi', 'Machakos','Nyamira','Kisii','Nyeri','Muranga','Isiolo','Mombasa' ]
random.sample(counties, k=2)

['Kisii', 'Nyamira']

## 2.0  Selecting the Random Sample from Dictionary

In [5]:
# Example 1
# ---
# We can select a random key-value pair from the dictionary as shown 
# ---
#
marks_dict = {
  "Kelly": 55,
  "jhon": 70,
  "Donald": 60,
  "Lennin" :50
}

print ("Choosing 2 random items from a dictionary using sample method ", random.sample(marks_dict.items(), k=2))

Choosing 2 random items from a dictionary using sample method  [('jhon', 70), ('Donald', 60)]

### <font color="green">2.0 Challenges</font>

In [6]:
# Challenge 1
# ---
# A caterer offers three different food packages; 
# bronze package: starch:rice stew:chicken curry vegetable:cabbages desert:melon
# silver package: starch:rice and chappati  stew:beef curry vegetable:spinach desert:melon and bananas
# gold package: starch:rice, chappati and mukimo stew: beef curry vegetable:spinach and managu desert: tart
# Create a dictionary that stores the above information and select a sample of size 2 
# ---
#
food_packages = {
        'bronze':{'starch':'rice', 'stew':'chicken curry','vegetable':'cabbage','desert':'melon' },
        'silver':{'starch':'rice and chappati', 'stew':'beef curry','vegetable':'spinach and managu','desert':'melon and bananas' },
        'gold':{'starch':'rice, chappati and mukimo', 'stew':'beef curry','vegetable':'spinach and managu','desert':'tart' }
    }
random.sample(food_packages.items(), k =2)

[('silver',
  {'starch': 'rice and chappati',
   'stew': 'beef curry',
   'vegetable': 'spinach and managu',
   'desert': 'melon and bananas'}),
 ('bronze',
  {'starch': 'rice',
   'stew': 'chicken curry',
   'vegetable': 'cabbage',
   'desert': 'melon'})]

## 3.0 Selecting a Random Sample with Replacement to including repetition

In [7]:
# Example 1
# ---
# We can select a random sample with replacement to include repetition as shown below
# ---
# 
names = ["Roger", "Nadal", "Novac", "Andre", "Sarena", "Mariya", "Martina"]

print("random sample with replacement to including repetition ", random.choices(names, k=3))

random sample with replacement to including repetition  ['Novac', 'Novac', 'Sarena']

### <font color="green">3.0 Challenges</font>

In [14]:
# Challenge 1
# ---
# Question: Select a random sample of 3 with replacement to include replacement from the 
# following list of months
# ---
#

months = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
          'August', 'September', 'October', 'November', 'December']

random.choices(months, k=3)

['April', 'March', 'April']

## 4.0 Selecting a Random Sample from a Range of Integers

In [9]:
# Example 1
# ---
# We can select a random sample from a range of integers as shown below
# ---
# 

weight_set = {40, 50, 55, 65, 75, 80}

print ("Choosing 4 random items from a set ", random.sample(weight_set, k=4))

Choosing 4 random items from a set  [55, 40, 65, 75]

### <font color="green">4.1 Challenges</font>

In [10]:
# Challenge 1
# ---
# Question: Select a random sample from a range of integers as shown below
# --- 
# 
weight_set = {4, 5, 6, 7, 8, 9, 10}
random.sample(weight_set, k=2)

[5, 4]

## 5.0 Selecting a Sample Array from a Large multidimensional Array

In [11]:
# Example 1
# ---
# We can select a sample array from a large multidimensional array as shown
# ---
# 

array = np.array([[2 ,4, 6], [5, 10, 15], [6, 12, 18], [7, 14, 21], [8, 16, 24]]) 
print("Printing 2D Array")
print(array)

# selecting multiple random rows from the 2D as shown
print("Selecting multiple random rows from the 2D array")
randomRows = np.random.randint(5, size=2)
for i in randomRows:
  print(array[i,:])

Printing 2D Array
[[ 2  4  6]
 [ 5 10 15]
 [ 6 12 18]
 [ 7 14 21]
 [ 8 16 24]]
Selecting multiple random rows from the 2D array
[ 6 12 18]
[ 7 14 21]

### <font color="green">5.0 Challenges</font>

In [12]:
# Challenge 1
# ---
# Question: Select two arrays from the given multidimensional array
# ---
# 

a = [[2, 4, 6, 8, 10], [3, 6, 9, 12, 15], [4, 8, 12, 16, 20], [1 ,2 , 4, 5, 6], [5, 10, 15, 20, 25], [6, 12, 18, 24, 30], [7, 14, 21, 28, 35]]  
random_arr = random.sample(a, k =2)
for ar in random_arr:
    print(ar)

[7, 14, 21, 28, 35]
[1, 2, 4, 5, 6]

## 6.0 Selecting Random Samples from a Dataset

In [13]:
# Example 1
# ---
# Selecting a random sample from the following medical appointments dataset
# ---
# Dataset url = http://bit.ly/MedicalAppointmentsDataset
# ---
# 

# Loading the dataset
medical_df = pd.read_csv("http://bit.ly/MedicalAppointmentsDataset")

# Determining the size
print(medical_df.shape)


# Previewing the dataset
print(medical_df.head())

# Selecting the sample 
medical_sample = medical_df.sample(n = 10, replace="False")
print(medical_sample)

KeyboardInterrupt:

### <font color="green">6.0 Challenges </font>

In [ ]:
# Challenge 1
# ---
# Select a random sample of 10 from the given dataset below 
# ---
# Dataset url = http://bit.ly/DSRussianInvestigation
# ---
#
df = pd.read_csv('http://bit.ly/DSRussianInvestigation')
df.sample(n = 10)

,investigation,investigation-start,investigation-end,investigation-days,name,indictment-days,type,cp-date,cp-days,overturned,pardoned,american,president
103,pierce,1990-03-01,1998-10-27,3162,Elaine Richardson,903.0,guilty-plea,1992-11-20,995.0,False,False,True,George H.W. Bush
134,whitewater,1994-08-05,2002-03-06,2770,Julie Hiatt Steele,1616.0,indictment,NaN,NaN,False,False,True,Bill Clinton
113,sealed-investigation-hwbush-2,1991-04-19,1992-07-15,453,NaN,NaN,NaN,NaN,NaN,False,False,True,George H.W. Bush
181,russia,2017-05-17,NaN,659,Russian national 15,422.0,indictment,NaN,NaN,False,False,False,Donald Trump
14,watergate,1973-05-19,1977-06-19,1492,Harry L. Sears,-9.0,indictment,NaN,NaN,False,False,True,Richard Nixon
128,whitewater,1994-08-05,2002-03-06,2770,Susan McDougal,377.0,conviction,1996-05-26,660.0,False,True,True,Bill Clinton
21,watergate,1973-05-19,1977-06-19,1492,Harry Heltzer,151.0,guilty-plea,1973-10-17,151.0,False,False,True,Richard Nixon
8,watergate,1973-05-19,1977-06-19,1492,G. Gordon Liddy,292.0,conviction,1974-07-12,419.0,False,False,True,Richard Nixon
109,pierce,1990-03-01,1998-10-27,3162,Ronald L. Mahon,1336.0,conviction,1994-06-23,1575.0,False,False,True,George H.W. Bush
178,russia,2017-05-17,NaN,659,Alex Van Der Zwaan,275.0,guilty-plea,2018-02-20,279.0,False,False,True,Donald Trump

In [ ]:
# Challenge 2
# ---
# A medical company would like to follow up with 50 patients who never showed up for appointments 
# but received an sms. Select a random sample from such patients given the medical dataset below 
# ---
# Dataset url = http://bit.ly/MedicalAppointmentsDataset
# ---
#
medical_df = pd.read_csv('http://bit.ly/MedicalAppointmentsDataset')
patients= medical_df[(medical_df['No-show']=='Yes')&(medical_df['SMS_received']==1)]
patients.sample(n=50)

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
77526,1.785254e+13,5695020,F,2016-05-13T09:19:54Z,2016-05-25T00:00:00Z,67,ANDORINHAS,0,1,1,0,0,1,Yes
62146,6.548814e+13,5517445,F,2016-03-28T16:36:31Z,2016-05-03T00:00:00Z,63,JABOUR,0,0,0,0,0,1,Yes
24025,4.269794e+11,5623036,F,2016-04-26T13:27:35Z,2016-05-10T00:00:00Z,39,SANTA MARTHA,0,0,0,0,0,1,Yes
57367,5.274990e+13,5552734,F,2016-04-06T16:56:59Z,2016-05-06T00:00:00Z,9,MARIA ORTIZ,0,0,0,0,0,1,Yes
55609,1.333540e+13,5725075,M,2016-05-20T10:31:38Z,2016-05-24T00:00:00Z,24,CONQUISTA,0,0,0,0,0,1,Yes
79952,4.835225e+12,5587046,F,2016-04-15T08:13:35Z,2016-05-03T00:00:00Z,84,PRAIA DO CANTO,0,0,0,0,0,1,Yes
56389,1.274762e+11,5619268,F,2016-04-26T07:51:12Z,2016-05-03T00:00:00Z,21,SÃO BENEDITO,0,0,0,1,0,1,Yes
26068,4.584171e+11,5629928,F,2016-04-27T14:22:21Z,2016-05-12T00:00:00Z,47,SANTO ANTÔNIO,0,0,0,0,0,1,Yes
57731,5.385874e+13,5643751,F,2016-05-02T07:50:31Z,2016-05-06T00:00:00Z,61,REDENÇÃO,0,1,1,0,0,1,Yes
57810,7.573515e+14,5642093,F,2016-04-29T15:03:29Z,2016-05-24T00:00:00Z,39,CONQUISTA,1,0,0,0,0,1,Yes
68856,7.837593e+13,5652678,F,2016-05-03T10:29:20Z,2016-05-12T00:00:00Z,53,TABUAZEIRO,0,0,0,0,0,1,Yes
6312,3.428460e+12,5609652,F,2016-04-20T16:31:35Z,2016-05-12T00:00:00Z,56,NOVA PALESTINA,0,1,0,0,0,1,Yes
56042,4.528231e+11,5639706,F,2016-04-29T09:25:35Z,2016-05-04T00:00:00Z,44,SANTO ANDRÉ,1,1,0,0,0,1,Yes
25083,7.165734e+13,5665870,M,2016-05-05T15:30:00Z,2016-05-24T00:00:00Z,32,ANDORINHAS,0,0,0,0,0,1,Yes
61356,7.556190e+12,5703966,F,2016-05-16T14:48:07Z,2016-05-25T00:00:00Z,2,CONSOLAÇÃO,0,0,0,0,0,1,Yes
1640,8.513189e+12,5618148,M,2016-04-26T06:32:51Z,2016-04-29T00:00:00Z,63,GURIGICA,0,1,1,0,0,1,Yes
64502,3.155531e+14,5671551,F,2016-05-06T18:15:51Z,2016-05-10T00:00:00Z,56,JARDIM CAMBURI,0,0,0,0,0,1,Yes
57057,6.845885e+13,5673282,M,2016-05-09T09:06:34Z,2016-05-30T00:00:00Z,6,VILA RUBIM,0,0,0,0,0,1,Yes
103523,9.413128e+13,5740558,F,2016-05-25T15:34:37Z,2016-06-07T00:00:00Z,19,SANTA MARTHA,1,0,0,0,0,1,Yes
105348,3.918526e+11,5708026,F,2016-05-17T10:30:17Z,2016-06-03T00:00:00Z,7,CRUZAMENTO,0,0,0,0,0,1,Yes
13734,2.378175e+13,5640756,F,2016-04-29T11:22:03Z,2016-05-02T00:00:00Z,31,CONSOLAÇÃO,1,0,0,0,0,1,Yes
23243,6.298618e+12,5630177,F,2016-04-27T14:54:20Z,2016-05-03T00:00:00Z,43,DA PENHA,1,0,0,0,0,1,Yes
52513,6.742636e+12,5630162,F,2016-04-27T14:52:21Z,2016-05-25T00:00:00Z,16,JESUS DE NAZARETH,1,0,0,0,0,1,Yes
82434,3.952634e+14,5594557,M,2016-04-18T10:54:04Z,2016-05-31T00:00:00Z,24,DA PENHA,0,0,0,0,0,1,Yes
87770,5.581628e+13,5718524,F,2016-05-19T09:37:37Z,2016-06-08T00:00:00Z,29,GRANDE VITÓRIA,0,0,0,0,0,1,Yes
82127,1.888826e+13,5601622,F,2016-04-19T13:22:00Z,2016-05-12T00:00:00Z,18,ITARARÉ,1,0,0,0,0,1,Yes
14420,5.951238e+11,5731739,F,2016-05-24T10:27:19Z,2016-05-30T00:00:00Z,71,INHANGUETÁ,0,1,1,0,0,1,Yes
108178,6.213695e+11,5740009,F,2016-05-25T14:33:44Z,2016-06-03T00:00:00Z,25,GRANDE VITÓRIA,0,0,0,0,0,1,Yes
85930,4.632487e+12,5576255,M,2016-04-13T08:13:06Z,2016-06-08T00:00:00Z,0,JARDIM CAMBURI,0,0,0,0,0,1,Yes
36959,8.665374e+12,5638045,F,2016-04-29T07:40:13Z,2016-05-02T00:00:00Z,10,RESISTÊNCIA,0,0,0,0,0,1,Yes
70018,9.363876e+12,5619174,F,2016-04-26T07:46:11Z,2016-05-06T00:00:00Z,33,SÃO PEDRO,1,0,0,1,0,1,Yes
104514,1.667435e+10,5768671,F,2016-06-03T07:53:14Z,2016-06-07T00:00:00Z,67,SÃO BENEDITO,0,1,1,0,0,1,Yes
2897,5.799226e+14,5547828,F,2016-04-06T07:44:09Z,2016-04-29T00:00:00Z,13,ILHA DE SANTA MARIA,0,0,0,0,0,1,Yes
37654,8.193513e+14,5624167,F,2016-04-26T15:21:45Z,2016-05-02T00:00:00Z,2,ARIOVALDO FAVALESSA,0,0,0,0,0,1,Yes
104783,8.453435e+13,5740620,F,2016-05-25T15:46:05Z,2016-06-02T00:00:00Z,41,SÃO CRISTÓVÃO,0,1,1,0,0,1,Yes
54253,6.376877e+14,5648096,F,2016-05-02T14:59:49Z,2016-05-11T00:00:00Z,14,ILHA DO PRÍNCIPE,0,0,0,0,0,1,Yes
54859,4.734564e+13,5625990,M,2016-04-27T07:47:04Z,2016-05-04T00:00:00Z,53,ILHA DO PRÍNCIPE,0,0,0,0,0,1,Yes
85882,4.759570e+11,5705353,M,2016-05-17T07:07:19Z,2016-06-02T00:00:00Z,53,BENTO FERREIRA,0,0,1,0,1,1,Yes
79189,4.588828e+12,5609364,F,2016-04-20T15:42:26Z,2016-05-25T00:00:00Z,47,TABUAZEIRO,0,1,0,0,1,1,Yes
105405,3.771713e+13,5749395,F,2016-05-31T07:45:43Z,2016-06-07T00:00:00Z,32,FORTE SÃO JOÃO,0,0,0,0,0,1,Yes
46523,9.962263e+13,5537445,F,2016-04-01T10:07:50Z,2016-05-03T00:00:00Z,25,MARIA ORTIZ,0,0,0,0,0,1,Yes
36964,4.736873e+13,5638062,M,2016-04-29T07:41:03Z,2016-05-02T00:00:00Z,6,RESISTÊNCIA,0,0,0,0,0,1,Yes
88609,1.123123e+12,5690629,F,2016-05-12T10:23:47Z,2016-06-02T00:00:00Z,22,INHANGUETÁ,0,0,0,0,0,1,Yes
26108,8.675975e+11,5540572,M,2016-04-05T07:10:10Z,2016-05-30T00:00:00Z,50,JOANA D´ARC,1,0,0,0,0,1,Yes
27731,4.293678e+14,5582280,F,2016-04-14T09:11:44Z,2016-05-10T00:00:00Z,45,SANTA CECÍLIA,0,0,0,0,0,1,Yes
67149,2.911597e+11,5419575,F,2016-03-02T09:12:59Z,2016-05-10T00:00:00Z,48,JARDIM CAMBURI,0,0,0,0,0,1,Yes
92942,7.677449e+12,5745237,M,2016-05-30T11:33:24Z,2016-06-08T00:00:00Z,26,SANTA LÚCIA,0,0,0,0,0,1,Yes
93977,9.171964e+11,5731681,F,2016-05-24T10:21:38Z,2016-06-07T00:00:00Z,1,SANTOS REIS,0,0,0,0,0,1,Yes
97469,3.882796e+13,5704583,F,2016-05-16T16:04:34Z,2016-06-06T00:00:00Z,66,CENTRO,0,1,0,0,0,1,Yes
101088,6.599564e+13,5709595,F,2016-05-17T14:02:30Z,2016-06-08T00:00:00Z,41,SANTO ANTÔNIO,0,0,0,0,0,1,Yes